--!strict
-- Lotus Library v1.1.0
-- Generated by scripts/build.py. Edit src/, not this file.
-- One-file Roblox Luau distribution; no external runtime dependencies.

--#region src/Prelude.lua
-- Core services and shared helpers. Kept dependency-free for one-file use.
local Players = game:GetService("Players")
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")

local Lotus = {
	Name = "lotus-library",
	Version = "1.1.0",
}

local function cloneTable(source)
	local copy = {}
	for key, value in pairs(source or {}) do
		copy[key] = type(value) == "table" and cloneTable(value) or value
	end
	return copy
end

local function mergeTable(base, overrides)
	local result = cloneTable(base)
	for key, value in pairs(overrides or {}) do
		if type(value) == "table" and type(result[key]) == "table" then
			result[key] = mergeTable(result[key], value)
		else
			result[key] = value
		end
	end
	return result
end

local function create(className, properties, children)
	local instance = Instance.new(className)
	for key, value in pairs(properties or {}) do
		if key ~= "Parent" then
			instance[key] = value
		end
	end
	for _, child in ipairs(children or {}) do
		child.Parent = instance
	end
	if properties and properties.Parent then
		instance.Parent = properties.Parent
	end
	return instance
end

local function corner(parent, radius)
	return create("UICorner", { CornerRadius = UDim.new(0, radius or 8), Parent = parent })
end

local function stroke(parent, color, transparency, thickness)
	return create("UIStroke", {
		Color = color,
		Transparency = transparency or 0,
		Thickness = thickness or 1,
		ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
		Parent = parent,
	})
end

local function padding(parent, left, right, top, bottom)
	return create("UIPadding", {
		PaddingLeft = UDim.new(0, left or 0),
		PaddingRight = UDim.new(0, right or left or 0),
		PaddingTop = UDim.new(0, top or left or 0),
		PaddingBottom = UDim.new(0, bottom or top or left or 0),
		Parent = parent,
	})
end

local function clamp(value, minimum, maximum)
	return math.max(minimum, math.min(maximum, value))
end

local function roundToStep(value, step)
	if not step or step <= 0 then
		return value
	end
	return math.floor((value / step) + 0.5) * step
end

local function safeCall(callback, ...)
	if type(callback) ~= "function" then
		return true
	end
	local ok, message = pcall(callback, ...)
	if not ok then
		warn("[Lotus] Callback error: " .. tostring(message))
	end
	return ok
end

local function normalizeOptions(value, titleKey)
	if type(value) == "string" then
		return { [titleKey or "Title"] = value }
	end
	return value or {}
end

local function resolveGuiParent(explicitParent)
	if explicitParent then
		return explicitParent
	end
	local player = Players.LocalPlayer
	assert(player, "[Lotus] Lotus.new must run on the client or receive config.Parent")
	return player:WaitForChild("PlayerGui")
end

local function formatNumber(value)
	if math.abs(value - math.floor(value)) < 0.00001 then
		return tostring(math.floor(value))
	end
	return string.format("%.2f", value):gsub("0+$", ""):gsub("%.$", "")
end
--#endregion src/Prelude.lua

--#region src/Util/Signal.lua
local Signal = {}
Signal.__index = Signal

function Signal.new()
	return setmetatable({
		_bindable = Instance.new("BindableEvent"),
		_destroyed = false,
	}, Signal)
end

function Signal:Connect(callback)
	assert(not self._destroyed, "Cannot connect to a destroyed Signal")
	assert(type(callback) == "function", "Signal callback must be a function")
	return self._bindable.Event:Connect(callback)
end

function Signal:Once(callback)
	local connection
	connection = self:Connect(function(...)
		connection:Disconnect()
		callback(...)
	end)
	return connection
end

function Signal:Fire(...)
	if not self._destroyed then
		self._bindable:Fire(...)
	end
end

function Signal:Wait()
	assert(not self._destroyed, "Cannot wait on a destroyed Signal")
	return self._bindable.Event:Wait()
end

function Signal:Destroy()
	if self._destroyed then
		return
	end
	self._destroyed = true
	self._bindable:Destroy()
end
--#endregion src/Util/Signal.lua

--#region src/Util/Maid.lua
local Maid = {}
Maid.__index = Maid

function Maid.new()
	return setmetatable({ _tasks = {}, _destroyed = false }, Maid)
end

function Maid:Give(taskValue)
	if taskValue == nil then
		return nil
	end
	if self._destroyed then
		self:_clean(taskValue)
		return taskValue
	end
	table.insert(self._tasks, taskValue)
	return taskValue
end

function Maid:_clean(taskValue)
	local kind = typeof(taskValue)
	if kind == "RBXScriptConnection" then
		taskValue:Disconnect()
	elseif kind == "Instance" then
		taskValue:Destroy()
	elseif type(taskValue) == "function" then
		taskValue()
	elseif type(taskValue) == "table" then
		if type(taskValue.Destroy) == "function" then
			taskValue:Destroy()
		elseif type(taskValue.Disconnect) == "function" then
			taskValue:Disconnect()
		end
	end
end

function Maid:Cleanup()
	for index = #self._tasks, 1, -1 do
		local taskValue = self._tasks[index]
		self._tasks[index] = nil
		local ok, message = pcall(function()
			self:_clean(taskValue)
		end)
		if not ok then
			warn("[Lotus] Cleanup error: " .. tostring(message))
		end
	end
end

function Maid:Destroy()
	if self._destroyed then
		return
	end
	self._destroyed = true
	self:Cleanup()
end
--#endregion src/Util/Maid.lua

--#region src/Util/Tween.lua
local Motion = {}

Motion.Fast = TweenInfo.new(0.14, Enum.EasingStyle.Quart, Enum.EasingDirection.Out)
Motion.Normal = TweenInfo.new(0.22, Enum.EasingStyle.Quart, Enum.EasingDirection.Out)
Motion.Slow = TweenInfo.new(0.42, Enum.EasingStyle.Quint, Enum.EasingDirection.Out)

function Motion.tween(instance, tweenInfo, properties)
	if not instance or not instance.Parent then
		return nil
	end
	local tween = TweenService:Create(instance, tweenInfo or Motion.Normal, properties)
	tween:Play()
	return tween
end

function Motion.press(button, scale)
	local uiScale = create("UIScale", { Scale = 1, Parent = button })
	local maid = Maid.new()
	maid:Give(button.MouseButton1Down:Connect(function()
		Motion.tween(uiScale, Motion.Fast, { Scale = scale or 0.97 })
	end))
	maid:Give(button.MouseButton1Up:Connect(function()
		Motion.tween(uiScale, Motion.Fast, { Scale = 1 })
	end))
	maid:Give(button.MouseLeave:Connect(function()
		Motion.tween(uiScale, Motion.Fast, { Scale = 1 })
	end))
	return maid
end
--#endregion src/Util/Tween.lua

--#region src/Theme.lua
local DEFAULT_THEME = {
	Background = Color3.fromRGB(8, 9, 10),
	Surface = Color3.fromRGB(15, 16, 17),
	SurfaceAlt = Color3.fromRGB(25, 26, 27),
	SurfaceHover = Color3.fromRGB(40, 40, 44),
	SurfaceMuted = Color3.fromRGB(20, 21, 22),
	Border = Color3.fromRGB(35, 37, 42),
	BorderStrong = Color3.fromRGB(52, 52, 58),
	Text = Color3.fromRGB(247, 248, 248),
	MutedText = Color3.fromRGB(138, 143, 152),
	SubtleText = Color3.fromRGB(98, 102, 109),
	Accent = Color3.fromRGB(94, 106, 210),
	AccentHover = Color3.fromRGB(113, 112, 255),
	AccentSoft = Color3.fromRGB(39, 42, 71),
	AccentText = Color3.fromRGB(255, 255, 255),
	Success = Color3.fromRGB(39, 166, 68),
	Warning = Color3.fromRGB(245, 158, 11),
	Danger = Color3.fromRGB(239, 68, 68),
	Overlay = Color3.fromRGB(1, 1, 2),
	Shadow = Color3.fromRGB(0, 0, 0),
}

Lotus.Themes = {
	Default = cloneTable(DEFAULT_THEME),
	Midnight = mergeTable(DEFAULT_THEME, {
		Background = Color3.fromRGB(5, 8, 15),
		Surface = Color3.fromRGB(10, 15, 26),
		SurfaceAlt = Color3.fromRGB(17, 24, 39),
		SurfaceHover = Color3.fromRGB(27, 38, 58),
		SurfaceMuted = Color3.fromRGB(12, 19, 32),
		Border = Color3.fromRGB(30, 41, 59),
		BorderStrong = Color3.fromRGB(51, 65, 85),
		Accent = Color3.fromRGB(99, 102, 241),
		AccentHover = Color3.fromRGB(129, 140, 248),
		AccentSoft = Color3.fromRGB(30, 32, 70),
	}),
	Rose = mergeTable(DEFAULT_THEME, {
		Background = Color3.fromRGB(16, 9, 13),
		Surface = Color3.fromRGB(25, 14, 21),
		SurfaceAlt = Color3.fromRGB(38, 21, 32),
		SurfaceHover = Color3.fromRGB(54, 29, 45),
		SurfaceMuted = Color3.fromRGB(29, 16, 24),
		Border = Color3.fromRGB(63, 35, 52),
		BorderStrong = Color3.fromRGB(88, 48, 72),
		Accent = Color3.fromRGB(244, 114, 182),
		AccentHover = Color3.fromRGB(251, 154, 205),
		AccentSoft = Color3.fromRGB(70, 30, 53),
	}),
	Graphite = mergeTable(DEFAULT_THEME, {
		Background = Color3.fromRGB(12, 12, 13),
		Surface = Color3.fromRGB(20, 20, 22),
		SurfaceAlt = Color3.fromRGB(29, 29, 32),
		SurfaceHover = Color3.fromRGB(43, 43, 47),
		SurfaceMuted = Color3.fromRGB(24, 24, 26),
		Border = Color3.fromRGB(46, 46, 51),
		BorderStrong = Color3.fromRGB(64, 64, 70),
		Accent = Color3.fromRGB(161, 161, 170),
		AccentHover = Color3.fromRGB(212, 212, 216),
		AccentSoft = Color3.fromRGB(52, 52, 58),
	}),
	Ocean = mergeTable(DEFAULT_THEME, {
		Background = Color3.fromRGB(4, 12, 18),
		Surface = Color3.fromRGB(7, 22, 31),
		SurfaceAlt = Color3.fromRGB(10, 34, 47),
		SurfaceHover = Color3.fromRGB(14, 48, 64),
		SurfaceMuted = Color3.fromRGB(8, 27, 37),
		Border = Color3.fromRGB(21, 55, 72),
		BorderStrong = Color3.fromRGB(30, 75, 95),
		Accent = Color3.fromRGB(14, 165, 233),
		AccentHover = Color3.fromRGB(56, 189, 248),
		AccentSoft = Color3.fromRGB(8, 56, 76),
	}),
	Emerald = mergeTable(DEFAULT_THEME, {
		Background = Color3.fromRGB(5, 13, 10),
		Surface = Color3.fromRGB(9, 24, 18),
		SurfaceAlt = Color3.fromRGB(13, 36, 27),
		SurfaceHover = Color3.fromRGB(18, 51, 38),
		SurfaceMuted = Color3.fromRGB(11, 29, 22),
		Border = Color3.fromRGB(24, 61, 46),
		BorderStrong = Color3.fromRGB(35, 83, 63),
		Accent = Color3.fromRGB(16, 185, 129),
		AccentHover = Color3.fromRGB(52, 211, 153),
		AccentSoft = Color3.fromRGB(14, 62, 47),
	}),
	Amber = mergeTable(DEFAULT_THEME, {
		Background = Color3.fromRGB(16, 11, 5),
		Surface = Color3.fromRGB(27, 19, 8),
		SurfaceAlt = Color3.fromRGB(41, 29, 11),
		SurfaceHover = Color3.fromRGB(57, 40, 14),
		SurfaceMuted = Color3.fromRGB(32, 23, 9),
		Border = Color3.fromRGB(69, 49, 17),
		BorderStrong = Color3.fromRGB(93, 65, 22),
		Accent = Color3.fromRGB(245, 158, 11),
		AccentHover = Color3.fromRGB(251, 191, 36),
		AccentSoft = Color3.fromRGB(76, 48, 11),
		AccentText = Color3.fromRGB(24, 16, 4),
	}),
	Light = mergeTable(DEFAULT_THEME, {
		Background = Color3.fromRGB(247, 248, 248),
		Surface = Color3.fromRGB(255, 255, 255),
		SurfaceAlt = Color3.fromRGB(243, 244, 245),
		SurfaceHover = Color3.fromRGB(232, 234, 237),
		SurfaceMuted = Color3.fromRGB(239, 240, 242),
		Border = Color3.fromRGB(214, 217, 222),
		BorderStrong = Color3.fromRGB(190, 195, 202),
		Text = Color3.fromRGB(24, 26, 29),
		MutedText = Color3.fromRGB(92, 97, 105),
		SubtleText = Color3.fromRGB(126, 132, 141),
		Accent = Color3.fromRGB(79, 70, 229),
		AccentHover = Color3.fromRGB(67, 56, 202),
		AccentSoft = Color3.fromRGB(224, 225, 252),
		Overlay = Color3.fromRGB(17, 24, 39),
		Shadow = Color3.fromRGB(31, 41, 55),
	}),
}

local activeTheme = cloneTable(DEFAULT_THEME)

function Lotus.ResolveTheme(theme)
	if theme == nil then
		return cloneTable(DEFAULT_THEME)
	end
	if type(theme) == "string" then
		local preset = Lotus.Themes[theme]
		assert(preset, "Unknown Lotus theme: " .. theme)
		return cloneTable(preset)
	end
	assert(type(theme) == "table", "Lotus theme must be a preset name or table")
	return mergeTable(DEFAULT_THEME, theme)
end

function Lotus.SetTheme(theme)
	activeTheme = Lotus.ResolveTheme(theme)
	return cloneTable(activeTheme)
end

function Lotus.GetTheme()
	return cloneTable(activeTheme)
end
--#endregion src/Theme.lua

--#region src/Components/Base.lua
local ComponentBase = {}
ComponentBase.__index = ComponentBase

function ComponentBase:_initialize(root)
	self.Root = root
	self._maid = Maid.new()
	self._destroyed = false
	self.Destroyed = Signal.new()
	self._maid:Give(self.Destroyed)
	return self
end

function ComponentBase:SetVisible(visible)
	if not self._destroyed then
		self.Root.Visible = visible == true
	end
	return self
end

function ComponentBase:Destroy()
	if self._destroyed then
		return
	end
	self._destroyed = true
	self.Destroyed:Fire()
	self._maid:Destroy()
	if self.Root then
		self.Root:Destroy()
	end
end

local function makeCard(section, height)
	local theme = section._window._theme
	local card = create("Frame", {
		Name = "Control",
		Size = UDim2.new(1, 0, 0, height),
		Active = true,
		BackgroundColor3 = theme.SurfaceMuted,
		BackgroundTransparency = 0.08,
		BorderSizePixel = 0,
		Parent = section._body,
	})
	corner(card, 8)
	stroke(card, theme.Border, 0.22, 1)
	card.MouseEnter:Connect(function()
		Motion.tween(card, Motion.Fast, { BackgroundColor3 = theme.SurfaceHover })
	end)
	card.MouseLeave:Connect(function()
		Motion.tween(card, Motion.Fast, { BackgroundColor3 = theme.SurfaceMuted })
	end)
	return card
end

local function makeControlText(card, options, rightInset, theme)
	theme = theme or activeTheme
	local title = options.Title or options.Name or options.Text or "Control"
	local description = options.Description
	local titleLabel = create("TextLabel", {
		Name = "Title",
		Position = UDim2.fromOffset(16, description and 10 or 0),
		Size = description and UDim2.new(1, -(rightInset or 130), 0, 20) or UDim2.new(1, -(rightInset or 130), 1, 0),
		BackgroundTransparency = 1,
		Font = Enum.Font.GothamMedium,
		Text = title,
		TextColor3 = theme.Text,
		TextSize = 13,
		TextXAlignment = Enum.TextXAlignment.Left,
		TextTruncate = Enum.TextTruncate.AtEnd,
		Parent = card,
	})
	local descriptionLabel
	if description then
		descriptionLabel = create("TextLabel", {
			Name = "Description",
			Position = UDim2.fromOffset(16, 30),
			Size = UDim2.new(1, -(rightInset or 130), 0, 18),
			BackgroundTransparency = 1,
			Font = Enum.Font.Gotham,
			Text = description,
			TextColor3 = theme.SubtleText,
			TextSize = 11,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextTruncate = Enum.TextTruncate.AtEnd,
			Parent = card,
		})
	end
	return titleLabel, descriptionLabel
end
--#endregion src/Components/Base.lua

--#region src/Components/Button.lua
local Button = setmetatable({}, ComponentBase)
Button.__index = Button

function Button.new(section, rawOptions)
	local options = normalizeOptions(rawOptions, "Title")
	local theme = section._window._theme
	local card = makeCard(section, options.Description and 60 or 52)
	local self = setmetatable({}, Button):_initialize(card)
	self._callback = options.Callback
	makeControlText(card, options, 124, theme)

	local action = create("TextButton", {
		Name = "Action",
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.new(1, -12, 0.5, 0),
		Size = UDim2.fromOffset(options.ButtonWidth or 92, 30),
		AutoButtonColor = false,
		BackgroundColor3 = theme.Accent,
		BorderSizePixel = 0,
		Font = Enum.Font.GothamMedium,
		Text = options.ButtonText or "Run",
		TextColor3 = theme.AccentText,
		TextSize = 12,
		Parent = card,
	})
	corner(action, 6)
	stroke(action, theme.AccentHover, 0.58, 1)
	self._maid:Give(Motion.press(action))
	self._maid:Give(action.MouseEnter:Connect(function()
		Motion.tween(action, Motion.Fast, { BackgroundColor3 = theme.AccentHover })
	end))
	self._maid:Give(action.MouseLeave:Connect(function()
		Motion.tween(action, Motion.Fast, { BackgroundColor3 = theme.Accent })
	end))
	self._maid:Give(action.Activated:Connect(function()
		safeCall(self._callback, self)
	end))
	self.Button = action
	return self
end

function Button:SetText(text)
	self.Button.Text = tostring(text)
	return self
end

function Button:Fire()
	safeCall(self._callback, self)
	return self
end
--#endregion src/Components/Button.lua

--#region src/Components/Toggle.lua
local Toggle = setmetatable({}, ComponentBase)
Toggle.__index = Toggle

function Toggle.new(section, rawOptions)
	local options = normalizeOptions(rawOptions, "Title")
	local theme = section._window._theme
	local card = makeCard(section, options.Description and 60 or 52)
	local self = setmetatable({}, Toggle):_initialize(card)
	self._sectionTheme = theme
	self.Value = options.Default == true
	self.Changed = Signal.new()
	self._maid:Give(self.Changed)
	makeControlText(card, options, 88, theme)

	local hitbox = create("TextButton", {
		Name = "ToggleHitbox",
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 1,
		Text = "",
		AutoButtonColor = false,
		Parent = card,
	})
	local track = create("Frame", {
		Name = "Track",
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.new(1, -16, 0.5, 0),
		Size = UDim2.fromOffset(42, 22),
		BackgroundColor3 = self.Value and theme.Accent or theme.BorderStrong,
		BorderSizePixel = 0,
		Parent = hitbox,
	})
	corner(track, 11)
	local thumb = create("Frame", {
		Name = "Thumb",
		AnchorPoint = Vector2.new(0, 0.5),
		Position = self.Value and UDim2.new(1, -19, 0.5, 0) or UDim2.new(0, 3, 0.5, 0),
		Size = UDim2.fromOffset(16, 16),
		BackgroundColor3 = theme.AccentText,
		BorderSizePixel = 0,
		Parent = track,
	})
	corner(thumb, 8)
	self.Track = track
	self.Thumb = thumb
	self._callback = options.Callback
	self._maid:Give(hitbox.Activated:Connect(function()
		self:Set(not self.Value)
	end))
	return self
end

function Toggle:Set(value, silent)
	value = value == true
	if self.Value == value then
		return self
	end
	self.Value = value
	local theme = self._sectionTheme or activeTheme
	Motion.tween(self.Track, Motion.Normal, {
		BackgroundColor3 = value and theme.Accent or theme.BorderStrong,
	})
	Motion.tween(self.Thumb, Motion.Normal, {
		Position = value and UDim2.new(1, -19, 0.5, 0) or UDim2.new(0, 3, 0.5, 0),
	})
	self.Changed:Fire(value)
	if not silent then
		safeCall(self._callback, value, self)
	end
	return self
end

function Toggle:Get()
	return self.Value
end
--#endregion src/Components/Toggle.lua

--#region src/Components/Slider.lua
local Slider = setmetatable({}, ComponentBase)
Slider.__index = Slider

function Slider.new(section, rawOptions)
	local options = normalizeOptions(rawOptions, "Title")
	local theme = section._window._theme
	local card = makeCard(section, options.Description and 84 or 72)
	local self = setmetatable({}, Slider):_initialize(card)
	self.Minimum = tonumber(options.Min) or 0
	self.Maximum = tonumber(options.Max) or 100
	assert(self.Maximum > self.Minimum, "Slider Max must be greater than Min")
	self.Step = tonumber(options.Step) or 1
	self.Suffix = options.Suffix or ""
	self.Value = nil
	self.Changed = Signal.new()
	self._maid:Give(self.Changed)
	self._callback = options.Callback
	makeControlText(card, options, 94, theme)

	local valueLabel = create("TextLabel", {
		Name = "Value",
		AnchorPoint = Vector2.new(1, 0),
		Position = UDim2.new(1, -16, 0, 10),
		Size = UDim2.fromOffset(80, 20),
		BackgroundTransparency = 1,
		Font = Enum.Font.GothamSemibold,
		Text = "",
		TextColor3 = theme.AccentHover,
		TextSize = 12,
		TextXAlignment = Enum.TextXAlignment.Right,
		Parent = card,
	})
	local track = create("Frame", {
		Name = "Track",
		AnchorPoint = Vector2.new(0, 1),
		Position = UDim2.new(0, 16, 1, -14),
		Size = UDim2.new(1, -32, 0, 4),
		BackgroundColor3 = theme.BorderStrong,
		BorderSizePixel = 0,
		Parent = card,
	})
	corner(track, 2)
	local fill = create("Frame", {
		Name = "Fill",
		Size = UDim2.fromScale(0, 1),
		BackgroundColor3 = theme.Accent,
		BorderSizePixel = 0,
		Parent = track,
	})
	corner(fill, 2)
	local thumb = create("Frame", {
		Name = "Thumb",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0, 0.5),
		Size = UDim2.fromOffset(14, 14),
		BackgroundColor3 = theme.AccentText,
		BorderSizePixel = 0,
		Parent = track,
	})
	corner(thumb, 7)
	stroke(thumb, theme.Accent, 0.15, 2)

	self.ValueLabel = valueLabel
	self.Track = track
	self.Fill = fill
	self.Thumb = thumb

	local dragging = false
	local function updateFromX(x)
		local width = math.max(track.AbsoluteSize.X, 1)
		local alpha = clamp((x - track.AbsolutePosition.X) / width, 0, 1)
		self:Set(self.Minimum + ((self.Maximum - self.Minimum) * alpha))
	end
	self._maid:Give(card.InputBegan:Connect(function(input)
		if
			input.UserInputType == Enum.UserInputType.MouseButton1
			or input.UserInputType == Enum.UserInputType.Touch
		then
			dragging = true
			updateFromX(input.Position.X)
		end
	end))
	self._maid:Give(UserInputService.InputChanged:Connect(function(input)
		if
			dragging
			and (
				input.UserInputType == Enum.UserInputType.MouseMovement
				or input.UserInputType == Enum.UserInputType.Touch
			)
		then
			updateFromX(input.Position.X)
		end
	end))
	self._maid:Give(UserInputService.InputEnded:Connect(function(input)
		if
			input.UserInputType == Enum.UserInputType.MouseButton1
			or input.UserInputType == Enum.UserInputType.Touch
		then
			dragging = false
		end
	end))

	self:Set(options.Default ~= nil and options.Default or self.Minimum, true)
	return self
end

function Slider:Set(value, silent)
	value = clamp(roundToStep(tonumber(value) or self.Minimum, self.Step), self.Minimum, self.Maximum)
	local changed = self.Value ~= value
	self.Value = value
	local alpha = (value - self.Minimum) / (self.Maximum - self.Minimum)
	self.ValueLabel.Text = formatNumber(value) .. self.Suffix
	Motion.tween(self.Fill, Motion.Fast, { Size = UDim2.fromScale(alpha, 1) })
	Motion.tween(self.Thumb, Motion.Fast, { Position = UDim2.fromScale(alpha, 0.5) })
	if changed then
		self.Changed:Fire(value)
		if not silent then
			safeCall(self._callback, value, self)
		end
	end
	return self
end

function Slider:Get()
	return self.Value
end
--#endregion src/Components/Slider.lua

--#region src/Components/Progress.lua
local Progress = setmetatable({}, ComponentBase)
Progress.__index = Progress

function Progress.new(section, rawOptions)
	local options = normalizeOptions(rawOptions, "Title")
	local theme = section._window._theme
	local card = makeCard(section, options.Description and 80 or 68)
	local self = setmetatable({}, Progress):_initialize(card)
	self.Minimum = tonumber(options.Min) or 0
	self.Maximum = tonumber(options.Max) or 100
	assert(self.Maximum > self.Minimum, "Progress Max must be greater than Min")
	self.Value = nil
	self.Changed = Signal.new()
	self._maid:Give(self.Changed)
	makeControlText(card, options, 84, theme)

	local valueLabel = create("TextLabel", {
		Name = "Value",
		AnchorPoint = Vector2.new(1, 0),
		Position = UDim2.new(1, -16, 0, 10),
		Size = UDim2.fromOffset(72, 20),
		BackgroundTransparency = 1,
		Font = Enum.Font.GothamSemibold,
		Text = "0%",
		TextColor3 = theme.MutedText,
		TextSize = 11,
		TextXAlignment = Enum.TextXAlignment.Right,
		Parent = card,
	})
	local track = create("Frame", {
		Name = "Track",
		AnchorPoint = Vector2.new(0, 1),
		Position = UDim2.new(0, 16, 1, -14),
		Size = UDim2.new(1, -32, 0, 5),
		BackgroundColor3 = theme.BorderStrong,
		BorderSizePixel = 0,
		Parent = card,
	})
	corner(track, 3)
	local fill = create("Frame", {
		Name = "Fill",
		Size = UDim2.fromScale(0, 1),
		BackgroundColor3 = options.Color or theme.Accent,
		BorderSizePixel = 0,
		Parent = track,
	})
	corner(fill, 3)
	self.ValueLabel = valueLabel
	self.Fill = fill
	self:Set(options.Value ~= nil and options.Value or self.Minimum)
	return self
end

function Progress:Set(value, label)
	value = clamp(tonumber(value) or self.Minimum, self.Minimum, self.Maximum)
	local changed = self.Value ~= value
	self.Value = value
	local alpha = (value - self.Minimum) / (self.Maximum - self.Minimum)
	self.ValueLabel.Text = label or (tostring(math.floor((alpha * 100) + 0.5)) .. "%")
	Motion.tween(self.Fill, Motion.Normal, { Size = UDim2.fromScale(alpha, 1) })
	if changed then
		self.Changed:Fire(value, alpha)
	end
	return self
end

function Progress:Get()
	return self.Value
end
--#endregion src/Components/Progress.lua

--#region src/Section.lua
local Section = {}
Section.__index = Section

function Section.new(tab, rawOptions)
	local options = normalizeOptions(rawOptions, "Title")
	local theme = tab._window._theme
	local self = setmetatable({}, Section)
	self._window = tab._window
	self._tab = tab
	self._maid = Maid.new()
	self._controls = {}

	local root = create("Frame", {
		Name = "Section_" .. tostring(options.Title or "Section"),
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 1,
		Parent = tab._page,
	})
	local title = create("TextLabel", {
		Name = "SectionTitle",
		Size = UDim2.new(1, 0, 0, 20),
		BackgroundTransparency = 1,
		Font = Enum.Font.GothamSemibold,
		Text = string.upper(options.Title or "SECTION"),
		TextColor3 = theme.SubtleText,
		TextSize = 11,
		TextXAlignment = Enum.TextXAlignment.Left,
		Parent = root,
	})
	local body = create("Frame", {
		Name = "Controls",
		Position = UDim2.fromOffset(0, 28),
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 1,
		Parent = root,
	})
	create("UIListLayout", {
		Padding = UDim.new(0, 8),
		FillDirection = Enum.FillDirection.Vertical,
		SortOrder = Enum.SortOrder.LayoutOrder,
		Parent = body,
	})
	create("UIPadding", {
		PaddingBottom = UDim.new(0, 2),
		Parent = body,
	})

	self.Root = root
	self._title = title
	self._body = body
	return self
end

function Section:SetTitle(title)
	self._title.Text = string.upper(tostring(title))
	return self
end

function Section:AddButton(options)
	local control = Button.new(self, options)
	table.insert(self._controls, control)
	return control
end

function Section:AddToggle(options)
	local control = Toggle.new(self, options)
	table.insert(self._controls, control)
	return control
end

function Section:AddSlider(options)
	local control = Slider.new(self, options)
	table.insert(self._controls, control)
	return control
end

function Section:AddProgress(options)
	local control = Progress.new(self, options)
	table.insert(self._controls, control)
	return control
end

function Section:Destroy()
	for index = #self._controls, 1, -1 do
		self._controls[index]:Destroy()
	end
	self._maid:Destroy()
	self.Root:Destroy()
end
--#endregion src/Section.lua

--#region src/Tab.lua
local Tab = {}
Tab.__index = Tab

function Tab.new(window, rawOptions)
	local options = normalizeOptions(rawOptions, "Name")
	local theme = window._theme
	local self = setmetatable({}, Tab)
	self._window = window
	self._maid = Maid.new()
	self._sections = {}
	self.Name = options.Name or options.Title or "Tab"
	self._icon = options.Icon

	local navButton = create("TextButton", {
		Name = "Tab_" .. self.Name,
		Size = UDim2.new(1, 0, 0, 40),
		AutoButtonColor = false,
		BackgroundColor3 = theme.AccentSoft,
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		Font = Enum.Font.GothamMedium,
		Text = "  " .. (options.Icon and (options.Icon .. "  ") or "") .. self.Name,
		TextColor3 = theme.MutedText,
		TextSize = 12,
		TextXAlignment = Enum.TextXAlignment.Left,
		Parent = window._nav,
	})
	corner(navButton, 6)
	local accent = create("Frame", {
		Name = "Accent",
		AnchorPoint = Vector2.new(0, 0.5),
		Position = UDim2.new(0, 5, 0.5, 0),
		Size = UDim2.fromOffset(2, 16),
		BackgroundColor3 = theme.Accent,
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		Parent = navButton,
	})
	corner(accent, 2)

	local page = create("ScrollingFrame", {
		Name = "Page_" .. self.Name,
		Size = UDim2.fromScale(1, 1),
		AutomaticCanvasSize = Enum.AutomaticSize.Y,
		CanvasSize = UDim2.new(),
		ScrollBarThickness = 2,
		ScrollBarImageColor3 = theme.Accent,
		ScrollBarImageTransparency = 0.45,
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		Visible = false,
		Parent = window._pages,
	})
	padding(page, 24, 24, 20, 24)
	create("UIListLayout", {
		Padding = UDim.new(0, 16),
		FillDirection = Enum.FillDirection.Vertical,
		SortOrder = Enum.SortOrder.LayoutOrder,
		Parent = page,
	})

	self._button = navButton
	self._accent = accent
	self._page = page
	self._maid:Give(navButton.Activated:Connect(function()
		window:SelectTab(self)
	end))
	self._maid:Give(navButton.MouseEnter:Connect(function()
		if window._activeTab ~= self then
			Motion.tween(navButton, Motion.Fast, { BackgroundTransparency = 0.45 })
		end
	end))
	self._maid:Give(navButton.MouseLeave:Connect(function()
		if window._activeTab ~= self then
			Motion.tween(navButton, Motion.Fast, { BackgroundTransparency = 1 })
		end
	end))
	return self
end

function Tab:_setActive(active)
	local theme = self._window._theme
	self._page.Visible = active
	Motion.tween(self._button, Motion.Normal, {
		BackgroundTransparency = active and 0.15 or 1,
		TextColor3 = active and theme.Text or theme.MutedText,
	})
	Motion.tween(self._accent, Motion.Normal, {
		BackgroundTransparency = active and 0 or 1,
	})
end

function Tab:AddSection(options)
	local section = Section.new(self, options)
	table.insert(self._sections, section)
	return section
end

function Tab:SetTitle(title)
	self.Name = tostring(title)
	self._button.Text = "  " .. (self._icon and (self._icon .. "  ") or "") .. self.Name
	return self
end

function Tab:Select()
	self._window:SelectTab(self)
	return self
end

function Tab:Destroy()
	for index = #self._sections, 1, -1 do
		self._sections[index]:Destroy()
	end
	self._maid:Destroy()
	self._button:Destroy()
	self._page:Destroy()
end
--#endregion src/Tab.lua

--#region src/Window.lua
local Window = {}
Window.__index = Window

local function makeIconButton(parent, text, offset, theme)
	local button = create("TextButton", {
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.new(1, offset, 0.5, 0),
		Size = UDim2.fromOffset(28, 28),
		AutoButtonColor = false,
		BackgroundColor3 = theme.SurfaceHover,
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		Font = Enum.Font.GothamMedium,
		Text = text,
		TextColor3 = theme.MutedText,
		TextSize = 16,
		Parent = parent,
	})
	corner(button, 6)
	button.MouseEnter:Connect(function()
		Motion.tween(button, Motion.Fast, {
			BackgroundTransparency = 0.08,
			TextColor3 = theme.Text,
		})
	end)
	button.MouseLeave:Connect(function()
		Motion.tween(button, Motion.Fast, {
			BackgroundTransparency = 1,
			TextColor3 = theme.MutedText,
		})
	end)
	return button
end

function Window.new(rawOptions)
	local options = rawOptions or {}
	local self = setmetatable({}, Window)
	self._maid = Maid.new()
	self._theme = type(options.Theme) == "string" and Lotus.ResolveTheme(options.Theme)
		or mergeTable(activeTheme, options.Theme)
	self._tabs = {}
	self._activeTab = nil
	self._destroyed = false
	self._minimized = false
	self._fullSize = options.Size or UDim2.fromOffset(720, 460)
	self.VisibilityChanged = Signal.new()
	self._maid:Give(self.VisibilityChanged)

	local parent = resolveGuiParent(options.Parent)
	local guiName = options.GuiName or "LotusLibrary"
	if options.SingleInstance ~= false then
		local previous = parent:FindFirstChild(guiName)
		if previous then
			previous:Destroy()
		end
	end

	local screenGui = create("ScreenGui", {
		Name = guiName,
		ResetOnSpawn = false,
		IgnoreGuiInset = false,
		ZIndexBehavior = Enum.ZIndexBehavior.Global,
		DisplayOrder = options.DisplayOrder or 50,
		Parent = parent,
	})
	self._maid:Give(screenGui)
	self.ScreenGui = screenGui

	local theme = self._theme
	local initialPosition = options.Position or UDim2.fromScale(0.5, 0.5)
	local shadow = create("Frame", {
		Name = "WindowShadow",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.new(
			initialPosition.X.Scale,
			initialPosition.X.Offset,
			initialPosition.Y.Scale,
			initialPosition.Y.Offset + 8
		),
		Size = self._fullSize,
		BackgroundColor3 = theme.Shadow,
		BackgroundTransparency = 0.52,
		BorderSizePixel = 0,
		Parent = screenGui,
	})
	corner(shadow, 16)
	local shadowSizeConstraint = create("UISizeConstraint", {
		MinSize = Vector2.new(560, 340),
		MaxSize = Vector2.new(1100, 760),
		Parent = shadow,
	})
	local shadowScale = create("UIScale", { Scale = 0.96, Parent = shadow })
	self._shadow = shadow
	self._shadowSizeConstraint = shadowSizeConstraint

	local main = create("Frame", {
		Name = "Window",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = initialPosition,
		Size = self._fullSize,
		BackgroundColor3 = self._theme.Background,
		BorderSizePixel = 0,
		ClipsDescendants = true,
		Parent = screenGui,
	})
	corner(main, 12)
	stroke(main, theme.BorderStrong, 0.35, 1)
	local sizeConstraint = create("UISizeConstraint", {
		MinSize = Vector2.new(560, 340),
		MaxSize = Vector2.new(1100, 760),
		Parent = main,
	})
	local scale = create("UIScale", { Scale = 0.96, Parent = main })
	self._sizeConstraint = sizeConstraint
	self.Main = main

	local sidebar = create("Frame", {
		Name = "Sidebar",
		Size = UDim2.new(0, options.SidebarWidth or 188, 1, 0),
		BackgroundColor3 = self._theme.Surface,
		BorderSizePixel = 0,
		Parent = main,
	})
	create("Frame", {
		Name = "Divider",
		AnchorPoint = Vector2.new(1, 0),
		Position = UDim2.fromScale(1, 0),
		Size = UDim2.new(0, 1, 1, 0),
		BackgroundColor3 = self._theme.Border,
		BackgroundTransparency = 0.35,
		BorderSizePixel = 0,
		Parent = sidebar,
	})
	local brandMark = create("Frame", {
		Name = "BrandMark",
		Position = UDim2.fromOffset(16, 18),
		Size = UDim2.fromOffset(32, 32),
		BackgroundColor3 = self._theme.Accent,
		BorderSizePixel = 0,
		Parent = sidebar,
	})
	corner(brandMark, 8)
	stroke(brandMark, self._theme.AccentHover, 0.58, 1)
	create("TextLabel", {
		Name = "Glyph",
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 1,
		Font = Enum.Font.GothamBold,
		Text = options.BrandGlyph or "L",
		TextColor3 = self._theme.AccentText,
		TextSize = 15,
		Parent = brandMark,
	})
	local sidebarTitle = create("TextLabel", {
		Name = "SidebarTitle",
		Position = UDim2.fromOffset(58, 17),
		Size = UDim2.new(1, -72, 0, 34),
		BackgroundTransparency = 1,
		Font = Enum.Font.GothamMedium,
		Text = options.SidebarTitle or options.Title or "LOTUS",
		TextColor3 = self._theme.Text,
		TextSize = 14,
		TextXAlignment = Enum.TextXAlignment.Left,
		TextTruncate = Enum.TextTruncate.AtEnd,
		Parent = sidebar,
	})
	local navCaption = create("TextLabel", {
		Name = "NavCaption",
		Position = UDim2.fromOffset(16, 70),
		Size = UDim2.new(1, -32, 0, 18),
		BackgroundTransparency = 1,
		Font = Enum.Font.GothamSemibold,
		Text = string.upper(options.NavTitle or "Navigation"),
		TextColor3 = self._theme.SubtleText,
		TextSize = 10,
		TextXAlignment = Enum.TextXAlignment.Left,
		Parent = sidebar,
	})
	local nav = create("ScrollingFrame", {
		Name = "Navigation",
		Position = UDim2.fromOffset(12, 94),
		Size = UDim2.new(1, -24, 1, -112),
		AutomaticCanvasSize = Enum.AutomaticSize.Y,
		CanvasSize = UDim2.new(),
		ScrollBarThickness = 0,
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		Parent = sidebar,
	})
	create("UIListLayout", {
		Padding = UDim.new(0, 5),
		FillDirection = Enum.FillDirection.Vertical,
		SortOrder = Enum.SortOrder.LayoutOrder,
		Parent = nav,
	})
	self._sidebarTitle = sidebarTitle
	self._navCaption = navCaption
	self._nav = nav

	local sidebarWidth = options.SidebarWidth or 188
	local topbar = create("Frame", {
		Name = "Topbar",
		Position = UDim2.fromOffset(sidebarWidth, 0),
		Size = UDim2.new(1, -sidebarWidth, 0, 68),
		BackgroundColor3 = self._theme.Background,
		BorderSizePixel = 0,
		Parent = main,
	})
	create("Frame", {
		Name = "Divider",
		AnchorPoint = Vector2.new(0, 1),
		Position = UDim2.fromScale(0, 1),
		Size = UDim2.new(1, 0, 0, 1),
		BackgroundColor3 = self._theme.Border,
		BackgroundTransparency = 0.45,
		BorderSizePixel = 0,
		Parent = topbar,
	})
	local titleLabel = create("TextLabel", {
		Name = "Title",
		Position = UDim2.fromOffset(24, 13),
		Size = UDim2.new(1, -120, 0, 22),
		BackgroundTransparency = 1,
		Font = Enum.Font.GothamMedium,
		Text = options.Title or "Lotus Menu",
		TextColor3 = self._theme.Text,
		TextSize = 15,
		TextXAlignment = Enum.TextXAlignment.Left,
		TextTruncate = Enum.TextTruncate.AtEnd,
		Parent = topbar,
	})
	local subtitleLabel = create("TextLabel", {
		Name = "Subtitle",
		Position = UDim2.fromOffset(24, 37),
		Size = UDim2.new(1, -120, 0, 16),
		BackgroundTransparency = 1,
		Font = Enum.Font.Gotham,
		Text = options.Subtitle or "Ready",
		TextColor3 = self._theme.SubtleText,
		TextSize = 10,
		TextXAlignment = Enum.TextXAlignment.Left,
		TextTruncate = Enum.TextTruncate.AtEnd,
		Parent = topbar,
	})
	self._titleLabel = titleLabel
	self._subtitleLabel = subtitleLabel

	local closeButton = makeIconButton(topbar, "×", -16, self._theme)
	closeButton.Name = "Close"
	local minimizeButton = makeIconButton(topbar, "–", -52, self._theme)
	minimizeButton.Name = "Minimize"
	self._maid:Give(closeButton.Activated:Connect(function()
		self:SetVisible(false)
	end))
	self._maid:Give(minimizeButton.Activated:Connect(function()
		self:SetMinimized(not self._minimized)
	end))

	local pages = create("Frame", {
		Name = "Pages",
		Position = UDim2.fromOffset(sidebarWidth, 68),
		Size = UDim2.new(1, -sidebarWidth, 1, -68),
		BackgroundTransparency = 1,
		Parent = main,
	})
	self._pages = pages

	local notificationHost = create("Frame", {
		Name = "Notifications",
		AnchorPoint = Vector2.new(1, 1),
		Position = UDim2.new(1, -18, 1, -18),
		Size = UDim2.fromOffset(310, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 1,
		Parent = screenGui,
	})
	create("UIListLayout", {
		Padding = UDim.new(0, 8),
		HorizontalAlignment = Enum.HorizontalAlignment.Right,
		VerticalAlignment = Enum.VerticalAlignment.Bottom,
		SortOrder = Enum.SortOrder.LayoutOrder,
		Parent = notificationHost,
	})
	self._notificationHost = notificationHost

	local dragging = false
	local dragStart
	local startPosition
	self._maid:Give(topbar.InputBegan:Connect(function(input)
		if
			input.UserInputType == Enum.UserInputType.MouseButton1
			or input.UserInputType == Enum.UserInputType.Touch
		then
			dragging = true
			dragStart = input.Position
			startPosition = main.Position
		end
	end))
	self._maid:Give(UserInputService.InputChanged:Connect(function(input)
		if
			dragging
			and (
				input.UserInputType == Enum.UserInputType.MouseMovement
				or input.UserInputType == Enum.UserInputType.Touch
			)
		then
			local delta = input.Position - dragStart
			local newPosition = UDim2.new(
				startPosition.X.Scale,
				startPosition.X.Offset + delta.X,
				startPosition.Y.Scale,
				startPosition.Y.Offset + delta.Y
			)
			main.Position = newPosition
			shadow.Position = UDim2.new(
				newPosition.X.Scale,
				newPosition.X.Offset,
				newPosition.Y.Scale,
				newPosition.Y.Offset + 8
			)
		end
	end))
	self._maid:Give(UserInputService.InputEnded:Connect(function(input)
		if
			input.UserInputType == Enum.UserInputType.MouseButton1
			or input.UserInputType == Enum.UserInputType.Touch
		then
			dragging = false
		end
	end))

	local toggleKey = options.ToggleKey == nil and Enum.KeyCode.RightShift or options.ToggleKey
	if toggleKey then
		self._maid:Give(UserInputService.InputBegan:Connect(function(input, gameProcessed)
			if not gameProcessed and input.KeyCode == toggleKey then
				self:SetVisible(not screenGui.Enabled)
			end
		end))
	end

	Motion.tween(scale, Motion.Slow, { Scale = 1 })
	Motion.tween(shadowScale, Motion.Slow, { Scale = 1 })
	self:_setupLoader(options.Loading)
	return self
end

function Window:_setupLoader(rawLoading)
	local config = rawLoading
	if config == false or (type(config) == "table" and config.Enabled == false) then
		return
	end
	if config == nil or config == true then
		config = {}
	end
	local theme = self._theme
	self.Main.Visible = false
	self._shadow.Visible = false
	local overlay = create("Frame", {
		Name = "LoadScreen",
		Size = UDim2.fromScale(1, 1),
		BackgroundColor3 = theme.Overlay,
		BackgroundTransparency = 0.08,
		BorderSizePixel = 0,
		Parent = self.ScreenGui,
	})
	local panel = create("Frame", {
		Name = "LoaderCard",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.5),
		Size = UDim2.fromOffset(360, 180),
		BackgroundColor3 = theme.Surface,
		BorderSizePixel = 0,
		Parent = overlay,
	})
	corner(panel, 12)
	stroke(panel, theme.BorderStrong, 0.28, 1)
	create("TextLabel", {
		Name = "LoaderTitle",
		Position = UDim2.fromOffset(24, 22),
		Size = UDim2.new(1, -48, 0, 26),
		BackgroundTransparency = 1,
		Font = Enum.Font.GothamMedium,
		Text = config.Title or self._titleLabel.Text,
		TextColor3 = theme.Text,
		TextSize = 18,
		TextXAlignment = Enum.TextXAlignment.Left,
		Parent = panel,
	})
	local status = create("TextLabel", {
		Name = "Status",
		Position = UDim2.fromOffset(24, 55),
		Size = UDim2.new(1, -48, 0, 20),
		BackgroundTransparency = 1,
		Font = Enum.Font.Gotham,
		Text = config.Text or "Loading interface…",
		TextColor3 = theme.SubtleText,
		TextSize = 11,
		TextXAlignment = Enum.TextXAlignment.Left,
		Parent = panel,
	})
	local percent = create("TextLabel", {
		Name = "Percent",
		AnchorPoint = Vector2.new(1, 0),
		Position = UDim2.new(1, -24, 0, 94),
		Size = UDim2.fromOffset(48, 18),
		BackgroundTransparency = 1,
		Font = Enum.Font.GothamSemibold,
		Text = "0%",
		TextColor3 = theme.AccentHover,
		TextSize = 11,
		TextXAlignment = Enum.TextXAlignment.Right,
		Parent = panel,
	})
	local track = create("Frame", {
		Name = "Track",
		Position = UDim2.fromOffset(24, 120),
		Size = UDim2.new(1, -48, 0, 5),
		BackgroundColor3 = theme.BorderStrong,
		BorderSizePixel = 0,
		Parent = panel,
	})
	corner(track, 3)
	local fill = create("Frame", {
		Name = "Fill",
		Size = UDim2.fromScale(0, 1),
		BackgroundColor3 = theme.Accent,
		BorderSizePixel = 0,
		Parent = track,
	})
	corner(fill, 3)
	self._loader = {
		Root = overlay,
		Panel = panel,
		Status = status,
		Percent = percent,
		Fill = fill,
	}

	if config.Auto ~= false then
		local duration = math.max(tonumber(config.Duration) or 1.15, 0.05)
		task.spawn(function()
			local started = os.clock()
			while not self._destroyed and self._loader do
				local alpha = clamp((os.clock() - started) / duration, 0, 1)
				self:SetLoadingProgress(alpha * 100)
				if alpha >= 1 then
					break
				end
				RunService.Heartbeat:Wait()
			end
			if not self._destroyed and self._loader then
				self:FinishLoading()
			end
		end)
	end
end

function Window:SetLoadingProgress(value, text)
	if not self._loader then
		return self
	end
	local alpha = clamp((tonumber(value) or 0) / 100, 0, 1)
	self._loader.Percent.Text = tostring(math.floor((alpha * 100) + 0.5)) .. "%"
	if text then
		self._loader.Status.Text = tostring(text)
	end
	Motion.tween(self._loader.Fill, Motion.Fast, { Size = UDim2.fromScale(alpha, 1) })
	return self
end

function Window:FinishLoading()
	local loader = self._loader
	if not loader then
		self.Main.Visible = true
		self._shadow.Visible = true
		return self
	end
	self._loader = nil
	Motion.tween(loader.Panel, Motion.Normal, { BackgroundTransparency = 1 })
	Motion.tween(loader.Root, Motion.Normal, { BackgroundTransparency = 1 })
	task.delay(0.22, function()
		if loader.Root then
			loader.Root:Destroy()
		end
		if not self._destroyed then
			self.Main.Visible = true
			self._shadow.Visible = true
		end
	end)
	return self
end

function Window:AddTab(options)
	assert(not self._destroyed, "Cannot add a tab to a destroyed Lotus window")
	local tab = Tab.new(self, options)
	table.insert(self._tabs, tab)
	if not self._activeTab then
		self:SelectTab(tab)
	end
	return tab
end

function Window:SelectTab(tabOrName)
	local selected = tabOrName
	if type(tabOrName) == "string" then
		selected = nil
		for _, tab in ipairs(self._tabs) do
			if tab.Name == tabOrName then
				selected = tab
				break
			end
		end
	end
	assert(selected and selected._window == self, "Tab does not belong to this Lotus window")
	self._activeTab = selected
	for _, tab in ipairs(self._tabs) do
		tab:_setActive(tab == selected)
	end
	return selected
end

function Window:SetTitle(title, subtitle)
	self._titleLabel.Text = tostring(title)
	if subtitle ~= nil then
		self._subtitleLabel.Text = tostring(subtitle)
	end
	return self
end

function Window:SetSidebarTitle(title, navTitle)
	self._sidebarTitle.Text = tostring(title)
	if navTitle ~= nil then
		self._navCaption.Text = string.upper(tostring(navTitle))
	end
	return self
end

function Window:SetVisible(visible)
	visible = visible == true
	self.ScreenGui.Enabled = visible
	self.VisibilityChanged:Fire(visible)
	return self
end

function Window:SetMinimized(minimized)
	minimized = minimized == true
	if self._minimized == minimized then
		return self
	end
	self._minimized = minimized
	if minimized then
		self._fullSize = self.Main.Size
		self._sizeConstraint.MinSize = Vector2.new(560, 68)
		self._shadowSizeConstraint.MinSize = Vector2.new(560, 68)
	else
		self._sizeConstraint.MinSize = Vector2.new(560, 340)
		self._shadowSizeConstraint.MinSize = Vector2.new(560, 340)
	end
	Motion.tween(self.Main, Motion.Slow, {
		Size = minimized and UDim2.new(self._fullSize.X.Scale, self._fullSize.X.Offset, 0, 68) or self._fullSize,
	})
	Motion.tween(self._shadow, Motion.Slow, {
		Size = minimized and UDim2.new(self._fullSize.X.Scale, self._fullSize.X.Offset, 0, 68) or self._fullSize,
	})
	return self
end

function Window:Notify(rawOptions)
	local options = normalizeOptions(rawOptions, "Title")
	local theme = self._theme
	local height = options.Description and 76 or 60
	local toast = create("Frame", {
		Name = "Notification",
		Size = UDim2.fromOffset(310, height),
		BackgroundColor3 = theme.SurfaceAlt,
		BorderSizePixel = 0,
		Parent = self._notificationHost,
	})
	corner(toast, 8)
	stroke(toast, theme.BorderStrong, 0.32, 1)
	local accent = create("Frame", {
		Name = "Accent",
		AnchorPoint = Vector2.new(0, 0.5),
		Position = UDim2.new(0, 16, 0.5, 0),
		Size = UDim2.fromOffset(8, 8),
		BackgroundColor3 = options.Color or theme.Accent,
		BorderSizePixel = 0,
		Parent = toast,
	})
	corner(accent, 4)
	create("TextLabel", {
		Name = "Title",
		Position = UDim2.fromOffset(36, options.Description and 13 or 0),
		Size = options.Description and UDim2.new(1, -52, 0, 20) or UDim2.new(1, -52, 1, 0),
		BackgroundTransparency = 1,
		Font = Enum.Font.GothamMedium,
		Text = options.Title or "Notification",
		TextColor3 = theme.Text,
		TextSize = 12,
		TextXAlignment = Enum.TextXAlignment.Left,
		TextTruncate = Enum.TextTruncate.AtEnd,
		Parent = toast,
	})
	if options.Description then
		create("TextLabel", {
			Name = "Description",
			Position = UDim2.fromOffset(36, 36),
			Size = UDim2.new(1, -52, 0, 24),
			BackgroundTransparency = 1,
			Font = Enum.Font.Gotham,
			Text = options.Description,
			TextColor3 = theme.SubtleText,
			TextSize = 10,
			TextWrapped = true,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextYAlignment = Enum.TextYAlignment.Top,
			Parent = toast,
		})
	end
	local toastScale = create("UIScale", { Scale = 0.92, Parent = toast })
	Motion.tween(toastScale, Motion.Normal, { Scale = 1 })
	task.delay(tonumber(options.Duration) or 3, function()
		if toast and toast.Parent then
			Motion.tween(toastScale, Motion.Normal, { Scale = 0.92 })
			Motion.tween(toast, Motion.Normal, { BackgroundTransparency = 1 })
			task.delay(0.22, function()
				if toast then
					toast:Destroy()
				end
			end)
		end
	end)
	return toast
end

function Window:Destroy()
	if self._destroyed then
		return
	end
	self._destroyed = true
	for index = #self._tabs, 1, -1 do
		self._tabs[index]:Destroy()
	end
	self._maid:Destroy()
end
--#endregion src/Window.lua

--#region src/init.lua
function Lotus.new(options)
	return Window.new(options)
end

Lotus.CreateWindow = Lotus.new

return Lotus
--#endregion src/init.lua
