from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROJECT_FILE = ROOT / "lotus.project.json"


def render_bundle() -> tuple[Path, str]:
    project = json.loads(PROJECT_FILE.read_text(encoding="utf-8"))
    version = project["version"]
    modules = project["modules"]
    output_path = ROOT / project["output"]

    chunks = [
        "--!strict\n",
        "-- Lotus Library v" + version + "\n",
        "-- Generated by scripts/build.py. Edit src/, not this file.\n",
        "-- One-file Roblox Luau distribution; no external runtime dependencies.\n\n",
    ]

    for relative_path in modules:
        source_path = ROOT / relative_path
        if not source_path.is_file():
            raise FileNotFoundError(f"Missing source module: {relative_path}")
        source = source_path.read_text(encoding="utf-8-sig").rstrip()
        chunks.extend(
            [
                f"--#region {relative_path}\n",
                source,
                "\n",
                f"--#endregion {relative_path}\n\n",
            ]
        )

    rendered = "".join(chunks).rstrip() + "\n"
    return output_path, rendered


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the Lotus one-file Luau distribution")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when dist/lotus-library.lua is not up to date",
    )
    args = parser.parse_args()

    output_path, rendered = render_bundle()
    digest = hashlib.sha256(rendered.encode("utf-8")).hexdigest()[:12]

    if args.check:
        if not output_path.is_file() or output_path.read_text(encoding="utf-8") != rendered:
            print(f"{output_path.relative_to(ROOT)} is out of date; run python scripts/build.py")
            return 1
        print(f"{output_path.relative_to(ROOT)} is up to date ({digest})")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Built {output_path.relative_to(ROOT)} ({len(rendered):,} bytes, sha256:{digest})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
